# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_pipelines/proto/ControllerService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model_pipelines/proto/ControllerService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-model_pipelines/proto/ControllerService.proto\"<\n\x0fPipelineRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x16\n\x0epipeline_steps\x18\x02 \x03(\t\"%\n\x0ePipelineOutput\x12\x13\n\x0b\x66inal_image\x18\x01 \x01(\x0c\x32I\n\x11\x43ontrollerService\x12\x34\n\x0fProcessPipeline\x12\x10.PipelineRequest\x1a\x0f.PipelineOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pipelines.proto.ControllerService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINEREQUEST']._serialized_start=49
  _globals['_PIPELINEREQUEST']._serialized_end=109
  _globals['_PIPELINEOUTPUT']._serialized_start=111
  _globals['_PIPELINEOUTPUT']._serialized_end=148
  _globals['_CONTROLLERSERVICE']._serialized_start=150
  _globals['_CONTROLLERSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
