# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_pipelines/proto/ModelService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model_pipelines/proto/ModelService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(model_pipelines/proto/ModelService.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"%\n\rImageResponse\x12\x14\n\x0cresult_image\x18\x01 \x01(\x0c\x32:\n\x0cModelService\x12*\n\x07Predict\x12\r.ImageRequest\x1a\x0e.ImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pipelines.proto.ModelService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=44
  _globals['_IMAGEREQUEST']._serialized_end=78
  _globals['_IMAGERESPONSE']._serialized_start=80
  _globals['_IMAGERESPONSE']._serialized_end=117
  _globals['_MODELSERVICE']._serialized_start=119
  _globals['_MODELSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
